#!/usr/bin/env python

import wp
import argparse

# wp script

parser=argparse.ArgumentParser()
parser.add_argument('-v', '--verbose', action='store_true', help='verbose output')
parser.add_argument('--version', action='version', version='%(prog)s '+wp.__version__)

# sub-parsers
subparsers=parser.add_subparsers()
# add
parser_add=subparsers.add_parser('add', description='add image(s) to wallpaper collection')
parser_add.add_argument('arg', nargs='+', help='image file(s) to add')
parser_add.set_defaults(func=wp.add)
# change
parser_change=subparsers.add_parser('change', description='change current wallpaper')
parser_change.add_argument('arg', nargs=1, help='image to set as wallpaper')
parser_change.set_defaults(func=wp.change)
# list
parser_list=subparsers.add_parser('list', description='list images in wallpaper collection')
parser_list.add_argument('-a', action='store_true', help='absolute path')
parser_list.set_defaults(func=wp.list)
# remove
parser_remove=subparsers.add_parser('remove', description='remove image(s) from wallpaper collection')
parser_remove.add_argument('arg', nargs='+', help='image(s) to remove')
parser_remove.set_defaults(func=wp.remove)

args=parser.parse_args()
args.func(args)

